-- V Mart initial schema. Run once in a new Supabase project, before seed.sql.
-- Connect your Firebase project in Supabase Authentication > Third-party Auth.
-- Firebase users need role='authenticated'; staff also need vmart_admin=true.
begin;
create table public.categories (
 id text primary key check(id ~ '^[a-z0-9-]+$'), name text not null check(length(name) between 1 and 100),
 image text not null default '', active boolean not null default true, sort_order integer not null default 100
);
create table public.products (
 id bigint generated by default as identity primary key,
 name text not null check(length(name) between 1 and 150), brand text not null default '',
 category text not null references public.categories(id), price numeric(12,2) not null check(price>0),
 mrp numeric(12,2) not null check(mrp>=price), unit text not null check(length(unit) between 1 and 40),
 stock integer not null default 0 check(stock between 0 and 100000), image text not null default '',
 description text not null default '' check(length(description)<=2000), featured boolean not null default false,
 active boolean not null default true, created_at timestamptz not null default now()
);
create table public.store_settings (
 id integer primary key check(id=1),name text not null,phone text not null,address text not null,city text not null,
 state text not null,pincode text not null check(pincode ~ '^\d{6}$'),hours text not null,
 delivery_fee numeric(10,2) not null default 30 check(delivery_fee>=0),
 free_delivery_threshold numeric(10,2) not null default 499 check(free_delivery_threshold>=0),
 service_pincodes text[] not null default array['572107']
);
create table public.profiles (
 uid text primary key,name text not null default '' check(length(name)<=80),phone text not null,
 address jsonb not null default '{"house":"","area":"","city":"Tumakuru","pin":"572107"}',created_at timestamptz not null default now()
);
create table public.carts (user_id text primary key,items jsonb not null default '{}' check(jsonb_typeof(items)='object' and octet_length(items::text)<20000),updated_at timestamptz not null default now());
create table public.wishlists (user_id text not null,product_id bigint not null references public.products(id) on delete cascade,primary key(user_id,product_id));
create table public.orders (
 id uuid primary key default gen_random_uuid(),user_id text not null,request_key uuid not null,
 customer_name text not null,phone text not null,items jsonb not null,subtotal numeric(12,2) not null,
 savings numeric(12,2) not null,delivery_fee numeric(10,2) not null,total numeric(12,2) not null,
 status text not null default 'Pending' check(status in ('Pending','Preparing','Out for delivery','Ready for pickup','Delivered','Cancelled')),
 fulfilment text not null check(fulfilment in ('delivery','pickup')),address jsonb not null,
 payment_status text not null default 'Pending' check(payment_status in ('Pending','Collected','Cancelled')),
 created_at timestamptz not null default now(),unique(user_id,request_key)
);
create index orders_user_created on public.orders(user_id,created_at desc);
create index orders_status on public.orders(status);
create index products_category_active on public.products(category,active);

create function public.is_store_admin() returns boolean language sql stable set search_path='' as $$
 select coalesce(auth.jwt()->>'vmart_admin'='true',false) and auth.jwt()->>'role'='authenticated';
$$;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.store_settings enable row level security;
alter table public.profiles enable row level security;
alter table public.carts enable row level security;
alter table public.wishlists enable row level security;
alter table public.orders enable row level security;

create policy category_read on public.categories for select to anon,authenticated using(active or (select public.is_store_admin()));
create policy category_manage on public.categories for all to authenticated using((select public.is_store_admin())) with check((select public.is_store_admin()));
create policy product_read on public.products for select to anon,authenticated using((active and exists(select 1 from public.categories c where c.id=category and c.active)) or (select public.is_store_admin()));
create policy product_manage on public.products for all to authenticated using((select public.is_store_admin())) with check((select public.is_store_admin()));
create policy settings_read on public.store_settings for select to anon,authenticated using(true);
create policy settings_manage on public.store_settings for update to authenticated using((select public.is_store_admin())) with check((select public.is_store_admin()));
create policy profile_own_read on public.profiles for select to authenticated using(uid=(select auth.jwt()->>'sub'));
create policy profile_own_insert on public.profiles for insert to authenticated with check(uid=(select auth.jwt()->>'sub') and phone=(select auth.jwt()->>'phone_number'));
create policy profile_own_update on public.profiles for update to authenticated using(uid=(select auth.jwt()->>'sub')) with check(uid=(select auth.jwt()->>'sub') and phone=(select auth.jwt()->>'phone_number'));
create policy cart_own on public.carts for all to authenticated using(user_id=(select auth.jwt()->>'sub')) with check(user_id=(select auth.jwt()->>'sub'));
create policy wishlist_own on public.wishlists for all to authenticated using(user_id=(select auth.jwt()->>'sub')) with check(user_id=(select auth.jwt()->>'sub'));
create policy orders_read on public.orders for select to authenticated using(user_id=(select auth.jwt()->>'sub') or (select public.is_store_admin()));

-- Orders cannot be inserted or edited directly. The RPC owns prices and inventory.
revoke all on public.categories,public.products,public.store_settings,public.profiles,public.carts,public.wishlists,public.orders from anon,authenticated;
grant select on public.categories,public.products,public.store_settings to anon,authenticated;
grant insert,update,delete on public.categories,public.products to authenticated;
grant update on public.store_settings to authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.carts,public.wishlists to authenticated;
grant select on public.orders to authenticated;
grant usage,select on sequence public.products_id_seq to authenticated;

create function public.place_order(basket jsonb,customer text,delivery_address jsonb,delivery_method text,request_key uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
 v_uid text:=auth.jwt()->>'sub'; mobile text:=auth.jwt()->>'phone_number';
 st public.store_settings%rowtype; p public.products%rowtype; result public.orders%rowtype;
 entry record; q integer; content jsonb:='[]'; sub numeric(12,2):=0; saved numeric(12,2):=0; fee numeric(10,2):=0;
begin
 if v_uid is null or coalesce(mobile,'')='' or coalesce(auth.jwt()->>'role','')<>'authenticated' then raise exception 'Please sign in with your phone number.';end if;
 if request_key is null then raise exception 'Missing checkout request.';end if;
 if length(trim(customer))<2 or length(customer)>80 then raise exception 'Enter your full name.';end if;
 if delivery_method not in ('delivery','pickup') then raise exception 'Choose delivery or pickup.';end if;
 if basket is null or jsonb_typeof(basket)<>'array' or jsonb_array_length(basket) not between 1 and 100 then raise exception 'Your basket must contain between 1 and 100 products.';end if;
 if exists(select 1 from jsonb_array_elements(basket) b where not (b ? 'id' and b ? 'qty') or coalesce(b->>'id','') !~ '^[0-9]{1,15}$' or coalesce(b->>'qty','') !~ '^[0-9]{1,2}$') then raise exception 'Invalid basket items.';end if;
 if (select count(*) from jsonb_array_elements(basket))<>(select count(distinct b->>'id') from jsonb_array_elements(basket) b) then raise exception 'Duplicate basket items.';end if;
 -- Lock a per-customer row to serialize retries and prevent duplicate stock deductions.
 insert into public.profiles(uid,name,phone) values(v_uid,trim(customer),mobile) on conflict do nothing;
 perform 1 from public.profiles pr where pr.uid=v_uid for update;
 select * into result from public.orders o where o.user_id=v_uid and o.request_key=place_order.request_key;
 if found then return to_jsonb(result);end if;
 select * into st from public.store_settings where id=1 for share;
 if not found then raise exception 'The store is not accepting orders yet.';end if;
 if delivery_method='delivery' then
  if jsonb_typeof(delivery_address)<>'object' or coalesce(length(trim(delivery_address->>'house')),0)<3 or coalesce(length(trim(delivery_address->>'area')),0)<2 or length(delivery_address::text)>2000 then raise exception 'Enter a complete delivery address.';end if;
  if coalesce(delivery_address->>'pin','')<>all(st.service_pincodes) or cardinality(st.service_pincodes)=0 then raise exception 'Delivery is not available for this pincode. Choose store pickup.';end if;
 end if;
 -- Stable product lock order prevents overselling and avoids cross-basket deadlocks.
 for entry in select (b->>'id')::bigint as id,(b->>'qty')::integer as qty from jsonb_array_elements(basket) b order by (b->>'id')::bigint loop
  q:=entry.qty;if q not between 1 and 99 then raise exception 'Invalid quantity.';end if;
  select * into p from public.products where id=entry.id for update;
  if not found then raise exception 'A product is no longer available.';end if;
  if not p.active or not exists(select 1 from public.categories c where c.id=p.category and c.active) then raise exception '% is not available.',p.name;end if;
  if p.stock<q then raise exception 'Only % of % are available. Please update your basket.',p.stock,p.name;end if;
  sub:=sub+p.price*q;saved:=saved+(p.mrp-p.price)*q;
  content:=content||jsonb_build_array(jsonb_build_object('id',p.id,'name',p.name,'unit',p.unit,'price',p.price,'mrp',p.mrp,'qty',q,'image',p.image));
  update public.products set stock=stock-q where id=p.id;
 end loop;
 if delivery_method='delivery' and sub<st.free_delivery_threshold then fee:=st.delivery_fee;end if;
 insert into public.orders(user_id,request_key,customer_name,phone,items,subtotal,savings,delivery_fee,total,fulfilment,address)
 values(v_uid,request_key,trim(customer),mobile,content,sub,saved,fee,sub+fee,delivery_method,case when delivery_method='pickup' then '{}'::jsonb else delivery_address||jsonb_build_object('city',st.city) end) returning * into result;
 update public.profiles pr set name=trim(customer),phone=mobile,address=case when delivery_method='delivery' then delivery_address||jsonb_build_object('city',st.city) else pr.address end where pr.uid=v_uid;
 delete from public.carts c where c.user_id=v_uid;
 return to_jsonb(result);
end;
$$;

create function public.set_order_status(order_id uuid,new_status text) returns jsonb language plpgsql security definer set search_path='' as $$
declare o public.orders%rowtype;entry record;
begin
 if not coalesce(public.is_store_admin(),false) then raise exception 'Administrator access required.';end if;
 select * into o from public.orders where id=order_id for update;
 if not found then raise exception 'Order not found.';end if;
 if o.status=new_status then return to_jsonb(o);end if;
 if o.status in ('Delivered','Cancelled') then raise exception 'This order is already complete.';end if;
 if new_status not in ('Preparing','Out for delivery','Ready for pickup','Delivered','Cancelled') then raise exception 'Invalid order status.';end if;
 if new_status='Preparing' and o.status<>'Pending' then raise exception 'The order has already moved past preparation.';end if;
 if new_status='Out for delivery' and (o.fulfilment<>'delivery' or o.status<>'Preparing') then raise exception 'Prepare the delivery order first.';end if;
 if new_status='Ready for pickup' and (o.fulfilment<>'pickup' or o.status<>'Preparing') then raise exception 'Prepare the pickup order first.';end if;
 if new_status='Delivered' and o.status not in ('Out for delivery','Ready for pickup') then raise exception 'The order must be dispatched or ready for pickup first.';end if;
 if new_status='Cancelled' then
  for entry in select (x->>'id')::bigint as id,(x->>'qty')::int as qty from jsonb_array_elements(o.items) x order by (x->>'id')::bigint loop
   update public.products set stock=stock+entry.qty where id=entry.id;
  end loop;
 end if;
 update public.orders set status=new_status,payment_status=case when new_status='Delivered' then 'Collected' when new_status='Cancelled' then 'Cancelled' else 'Pending' end where id=o.id returning * into o;
 return to_jsonb(o);
end;
$$;
revoke all on function public.is_store_admin() from public;
grant execute on function public.is_store_admin() to anon,authenticated;
revoke all on function public.place_order(jsonb,text,jsonb,text,uuid) from public;
grant execute on function public.place_order(jsonb,text,jsonb,text,uuid) to authenticated;
revoke all on function public.set_order_status(uuid,text) from public;
grant execute on function public.set_order_status(uuid,text) to authenticated;
commit;

-- Optional product photo uploads. Supabase Storage is not used for customer data.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('product-images','product-images',true,5242880,array['image/png','image/jpeg','image/webp']) on conflict(id) do nothing;
create policy vmart_images_read on storage.objects for select to anon,authenticated using(bucket_id='product-images');
create policy vmart_images_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and (select public.is_store_admin()));
create policy vmart_images_update on storage.objects for update to authenticated using(bucket_id='product-images' and (select public.is_store_admin())) with check(bucket_id='product-images' and (select public.is_store_admin()));
create policy vmart_images_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and (select public.is_store_admin()));
