'use client';
import {useEffect,useRef,useState} from 'react';
import {RecaptchaVerifier,signInWithPhoneNumber,type ConfirmationResult} from 'firebase/auth';
import {ShieldCheck,ShoppingBasket,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {useStore} from '@/lib/store';
import {services,ensureRole,readableError} from '@/lib/services';
export function AuthDialog(){
 const s=useStore();const [step,setStep]=useState<'phone'|'otp'|'name'>('phone'),[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[countdown,setCountdown]=useState(0),[consent,setConsent]=useState(false);
 const confirmation=useRef<ConfirmationResult|null>(null),recaptcha=useRef<RecaptchaVerifier|null>(null);
 useEffect(()=>{if(countdown<=0)return;const t=setTimeout(()=>setCountdown(n=>n-1),1000);return()=>clearTimeout(t);},[countdown]);
 useEffect(()=>{if(s.loginOpen){setStep(s.user?'name':'phone');setError('');setName(s.profile?.name||'');}else{recaptcha.current?.clear();recaptcha.current=null;setOtp('');}return()=>{};},[s.loginOpen]);
 async function send(e?:React.FormEvent){e?.preventDefault();setError('');if(!/^[6-9]\d{9}$/.test(phone)){setError('Enter a valid 10-digit mobile number.');return;}if(!consent){setError('Please agree to receive a verification SMS.');return;}setBusy(true);try{const {auth}=await services();if(!auth)throw Error('Phone sign-in will be available when the store opens. You can keep browsing for now.');if(!recaptcha.current)recaptcha.current=new RecaptchaVerifier(auth,'phone-recaptcha',{size:'invisible'});confirmation.current=await signInWithPhoneNumber(auth,'+91'+phone,recaptcha.current);setStep('otp');setCountdown(60);}catch(e){setError(readableError(e));recaptcha.current?.clear();recaptcha.current=null;}finally{setBusy(false);}}
 async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!confirmation.current)throw Error('Please request a new code.');const {user}=await confirmation.current.confirm(otp);await ensureRole();const {db}=await services();const {data,error}=db?await db.from('profiles').select('name').eq('uid',user.uid).maybeSingle():{data:null,error:null};if(error)throw Error('Unable to load your account. Please try again.');if(data?.name)s.setLoginOpen(false);else setStep('name');}catch(e){setError(readableError(e));}finally{setBusy(false);}}
 async function finish(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!s.user)throw Error('Please sign in again.');await s.saveProfile({uid:s.user.uid,name:name.trim(),phone:s.user.phoneNumber||'',address:s.profile?.address||{house:'',area:'',city:'Tumakuru',pin:'572107'}});s.setLoginOpen(false);}catch(e){setError(readableError(e));}finally{setBusy(false);}}
 return <Dialog modal={false} open={s.loginOpen} onOpenChange={v=>!busy&&s.setLoginOpen(v)}><DialogContent className="auth-dialog" aria-describedby="auth-description" onInteractOutside={e=>e.preventDefault()}><aside className="auth-art"><div className="brand light">v<span>mart</span><i/></div><ShoppingBasket size={70} strokeWidth={1}/><h2>A little more fresh.<br/>A lot more value.</h2><p>Your neighbourhood store,<br/>now at your doorstep.</p><span><ShieldCheck size={16}/> Safe & secure sign-in</span></aside><div className="auth-content"><div className="eyebrow">WELCOME TO V MART</div><DialogTitle>{step==='phone'?'Let’s get you logged in':step==='otp'?'Check your messages':'Nice to meet you'}</DialogTitle><DialogDescription id="auth-description">{step==='phone'?'Enter your mobile number to get started.':step==='otp'?`Enter the 6-digit code sent to +91 ${phone}.`:'What should we call you?'}</DialogDescription>{step==='phone'?<form onSubmit={send}><label htmlFor="phone">Mobile number</label><div className="phone-field"><span>+91</span><input id="phone" type="tel" inputMode="numeric" autoComplete="tel-national" maxLength={10} placeholder="Enter 10-digit number" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))}/></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to receive a sign-in SMS. Google processes my number for verification and abuse prevention.</span></label><button className="primary full" disabled={busy||phone.length!==10||!consent}>{busy?'Sending code…':'Get OTP'}</button><p className="form-foot">No passwords to remember. Just your phone.</p></form>:step==='otp'?<form onSubmit={verify}><InputOTP maxLength={6} value={otp} onChange={setOtp} autoComplete="one-time-code" pattern="^[0-9]*$" aria-label="Six digit verification code"><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP><button className="primary full" disabled={busy||otp.length!==6}>{busy?'Verifying…':'Verify & continue'}</button><button className="text-button" type="button" onClick={()=>send()} disabled={busy||countdown>0}>{countdown>0?`Resend code in ${countdown}s`:'Resend OTP'}</button><button className="text-button" type="button" onClick={()=>{setStep('phone');setOtp('');}} disabled={busy}>Change mobile number</button></form>:<form onSubmit={finish}><label htmlFor="name">Your name</label><input id="name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} maxLength={80} minLength={2} required placeholder="First and last name"/><button className="primary full" disabled={busy||name.trim().length<2}>{busy?'Saving…':'Save & start shopping'}<Check size={16}/></button></form>}{error&&<p className="form-error" role="alert">{error}</p>}<div id="phone-recaptcha"/></div></DialogContent></Dialog>;
}
