export type Product = { id:number; name:string; brand:string; category:string; price:number; mrp:number; unit:string; stock:number; featured:boolean; description:string; active:boolean; image:string };
export type Category = {id:string;name:string;image:string;active:boolean};
export const seedProducts:Product[] = [
  {
    "id": 1,
    "name": "Amul Milk",
    "brand": "Amul",
    "category": "dairy",
    "price": 33,
    "mrp": 33,
    "unit": "500 ml",
    "stock": 80,
    "featured": true,
    "description": "Fresh toned milk.",
    "active": true,
    "image": ""
  },
  {
    "id": 2,
    "name": "Amul Butter",
    "brand": "Amul",
    "category": "dairy",
    "price": 56,
    "mrp": 60,
    "unit": "100 g",
    "stock": 40,
    "featured": true,
    "description": "Creamy salted table butter.",
    "active": true,
    "image": ""
  },
  {
    "id": 3,
    "name": "Amul Curd",
    "brand": "Amul",
    "category": "dairy",
    "price": 40,
    "mrp": 44,
    "unit": "400 g",
    "stock": 36,
    "featured": false,
    "description": "Thick, fresh dahi.",
    "active": true,
    "image": ""
  },
  {
    "id": 4,
    "name": "Aashirvaad Atta",
    "brand": "Aashirvaad",
    "category": "atta",
    "price": 255,
    "mrp": 280,
    "unit": "5 kg",
    "stock": 24,
    "featured": true,
    "description": "Whole wheat atta for soft rotis.",
    "active": true,
    "image": ""
  },
  {
    "id": 5,
    "name": "India Gate Basmati Rice",
    "brand": "India Gate",
    "category": "rice",
    "price": 320,
    "mrp": 360,
    "unit": "5 kg",
    "stock": 20,
    "featured": true,
    "description": "Long-grain aged basmati rice.",
    "active": true,
    "image": ""
  },
  {
    "id": 6,
    "name": "Tata Salt",
    "brand": "Tata",
    "category": "oil",
    "price": 22,
    "mrp": 25,
    "unit": "1 kg",
    "stock": 60,
    "featured": false,
    "description": "Iodised free-flow salt.",
    "active": true,
    "image": ""
  },
  {
    "id": 7,
    "name": "Fortune Sunflower Oil",
    "brand": "Fortune",
    "category": "oil",
    "price": 149,
    "mrp": 165,
    "unit": "1 L",
    "stock": 35,
    "featured": true,
    "description": "Light refined sunflower oil.",
    "active": true,
    "image": ""
  },
  {
    "id": 8,
    "name": "Tata Tea Gold",
    "brand": "Tata",
    "category": "beverages",
    "price": 245,
    "mrp": 270,
    "unit": "1 kg",
    "stock": 28,
    "featured": true,
    "description": "Rich, aromatic blended tea leaves.",
    "active": true,
    "image": ""
  },
  {
    "id": 9,
    "name": "Maggi Noodles",
    "brand": "Nestlé",
    "category": "snacks",
    "price": 56,
    "mrp": 60,
    "unit": "4-pack",
    "stock": 90,
    "featured": true,
    "description": "2-minute masala instant noodles.",
    "active": true,
    "image": ""
  },
  {
    "id": 10,
    "name": "Britannia Good Day",
    "brand": "Britannia",
    "category": "snacks",
    "price": 35,
    "mrp": 40,
    "unit": "250 g",
    "stock": 70,
    "featured": false,
    "description": "Cashew butter cookies.",
    "active": true,
    "image": ""
  },
  {
    "id": 11,
    "name": "Parle-G Biscuits",
    "brand": "Parle",
    "category": "snacks",
    "price": 20,
    "mrp": 22,
    "unit": "200 g",
    "stock": 100,
    "featured": false,
    "description": "Classic glucose biscuits.",
    "active": true,
    "image": ""
  },
  {
    "id": 12,
    "name": "Coca-Cola",
    "brand": "Coca-Cola",
    "category": "beverages",
    "price": 45,
    "mrp": 50,
    "unit": "750 ml",
    "stock": 50,
    "featured": false,
    "description": "Chilled soft drink.",
    "active": true,
    "image": ""
  },
  {
    "id": 13,
    "name": "Pepsi",
    "brand": "Pepsi",
    "category": "beverages",
    "price": 45,
    "mrp": 50,
    "unit": "750 ml",
    "stock": 50,
    "featured": false,
    "description": "Chilled soft drink.",
    "active": true,
    "image": ""
  },
  {
    "id": 14,
    "name": "Colgate Strong Teeth",
    "brand": "Colgate",
    "category": "personal",
    "price": 89,
    "mrp": 99,
    "unit": "200 g",
    "stock": 55,
    "featured": false,
    "description": "Cavity protection toothpaste.",
    "active": true,
    "image": ""
  },
  {
    "id": 15,
    "name": "Surf Excel",
    "brand": "Surf Excel",
    "category": "household",
    "price": 210,
    "mrp": 230,
    "unit": "1 kg",
    "stock": 32,
    "featured": true,
    "description": "Removes tough stains.",
    "active": true,
    "image": ""
  },
  {
    "id": 16,
    "name": "Fresh Apples",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 189,
    "mrp": 210,
    "unit": "1 kg",
    "stock": 45,
    "featured": true,
    "description": "Crisp, hand-picked apples.",
    "active": true,
    "image": ""
  },
  {
    "id": 17,
    "name": "Fresh Bananas",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 49,
    "mrp": 49,
    "unit": "1 dozen",
    "stock": 50,
    "featured": true,
    "description": "Ripe, naturally sweet bananas.",
    "active": true,
    "image": ""
  },
  {
    "id": 18,
    "name": "Fresh Tomatoes",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 35,
    "mrp": 40,
    "unit": "1 kg",
    "stock": 40,
    "featured": false,
    "description": "Juicy farm-fresh tomatoes.",
    "active": true,
    "image": ""
  },
  {
    "id": 19,
    "name": "Fresh Potatoes",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 28,
    "mrp": 32,
    "unit": "1 kg",
    "stock": 55,
    "featured": false,
    "description": "Everyday cooking potatoes.",
    "active": true,
    "image": ""
  },
  {
    "id": 20,
    "name": "Fresh Onions",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 32,
    "mrp": 36,
    "unit": "1 kg",
    "stock": 60,
    "featured": false,
    "description": "Everyday cooking onions.",
    "active": true,
    "image": ""
  },
  {
    "id": 21,
    "name": "Fresh Carrots",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 38,
    "mrp": 42,
    "unit": "500 g",
    "stock": 30,
    "featured": false,
    "description": "Crunchy fresh carrots.",
    "active": true,
    "image": ""
  },
  {
    "id": 22,
    "name": "Fresh Oranges",
    "brand": "Farm Fresh",
    "category": "fruits",
    "price": 99,
    "mrp": 110,
    "unit": "1 kg",
    "stock": 26,
    "featured": false,
    "description": "Juicy seasonal oranges.",
    "active": true,
    "image": ""
  },
  {
    "id": 23,
    "name": "Bisleri Water",
    "brand": "Bisleri",
    "category": "beverages",
    "price": 20,
    "mrp": 20,
    "unit": "1 L",
    "stock": 70,
    "featured": false,
    "description": "Packaged drinking water.",
    "active": true,
    "image": ""
  },
  {
    "id": 24,
    "name": "Dairy Milk Chocolate",
    "brand": "Cadbury",
    "category": "chocolates",
    "price": 45,
    "mrp": 50,
    "unit": "50 g",
    "stock": 60,
    "featured": true,
    "description": "Classic creamy milk chocolate.",
    "active": true,
    "image": ""
  },
  {
    "id": 25,
    "name": "Dettol Handwash",
    "brand": "Dettol",
    "category": "personal",
    "price": 99,
    "mrp": 110,
    "unit": "200 ml",
    "stock": 34,
    "featured": false,
    "description": "Germ protection handwash.",
    "active": true,
    "image": ""
  },
  {
    "id": 26,
    "name": "Lux Soap",
    "brand": "Lux",
    "category": "personal",
    "price": 38,
    "mrp": 42,
    "unit": "3-pack",
    "stock": 44,
    "featured": false,
    "description": "Fragrant beauty soap.",
    "active": true,
    "image": ""
  },
  {
    "id": 27,
    "name": "Dove Shampoo",
    "brand": "Dove",
    "category": "personal",
    "price": 175,
    "mrp": 195,
    "unit": "340 ml",
    "stock": 26,
    "featured": false,
    "description": "Nourishing daily shampoo.",
    "active": true,
    "image": ""
  },
  {
    "id": 28,
    "name": "Ariel Detergent",
    "brand": "Ariel",
    "category": "household",
    "price": 225,
    "mrp": 250,
    "unit": "1 kg",
    "stock": 28,
    "featured": false,
    "description": "Powerful stain removal powder.",
    "active": true,
    "image": ""
  },
  {
    "id": 29,
    "name": "Vim Dishwash",
    "brand": "Vim",
    "category": "household",
    "price": 99,
    "mrp": 110,
    "unit": "500 ml",
    "stock": 30,
    "featured": false,
    "description": "Lemon-fresh dishwash gel.",
    "active": true,
    "image": ""
  },
  {
    "id": 30,
    "name": "Whole Wheat Bread",
    "brand": "Modern",
    "category": "bakery",
    "price": 45,
    "mrp": 48,
    "unit": "400 g",
    "stock": 26,
    "featured": true,
    "description": "Soft, fibre-rich sandwich bread.",
    "active": true,
    "image": ""
  },
  {
    "id": 31,
    "name": "Toor Dal",
    "brand": "Tata Sampann",
    "category": "pulses",
    "price": 145,
    "mrp": 160,
    "unit": "1 kg",
    "stock": 32,
    "featured": false,
    "description": "Unpolished toor dal.",
    "active": true,
    "image": ""
  },
  {
    "id": 32,
    "name": "Johnson's Baby Powder",
    "brand": "Johnson's",
    "category": "baby",
    "price": 135,
    "mrp": 150,
    "unit": "200 g",
    "stock": 20,
    "featured": false,
    "description": "Gentle everyday baby powder.",
    "active": true,
    "image": ""
  }
];
export const seedCategories:Category[] = [
  {
    "id": "fruits",
    "name": "Fruits & Vegetables",
    "image": "",
    "active": true
  },
  {
    "id": "dairy",
    "name": "Dairy & Milk",
    "image": "",
    "active": true
  },
  {
    "id": "rice",
    "name": "Rice & Grains",
    "image": "",
    "active": true
  },
  {
    "id": "atta",
    "name": "Atta & Flour",
    "image": "",
    "active": true
  },
  {
    "id": "pulses",
    "name": "Pulses",
    "image": "",
    "active": true
  },
  {
    "id": "oil",
    "name": "Oil & Masala",
    "image": "",
    "active": true
  },
  {
    "id": "snacks",
    "name": "Biscuits & Snacks",
    "image": "",
    "active": true
  },
  {
    "id": "beverages",
    "name": "Beverages",
    "image": "",
    "active": true
  },
  {
    "id": "chocolates",
    "name": "Chocolates",
    "image": "",
    "active": true
  },
  {
    "id": "bakery",
    "name": "Bakery",
    "image": "",
    "active": true
  },
  {
    "id": "personal",
    "name": "Personal Care",
    "image": "",
    "active": true
  },
  {
    "id": "household",
    "name": "Household",
    "image": "",
    "active": true
  },
  {
    "id": "baby",
    "name": "Baby Care",
    "image": "",
    "active": true
  },
  {
    "id": "frozen",
    "name": "Frozen Foods",
    "image": "",
    "active": true
  }
];
export const defaultSettings = {id:1,name:'V Mart',phone:'081053 24989',address:'Vishwabharati College Road, Near Busstand, Mallasandra',city:'Tumakuru',state:'Karnataka',pincode:'572107',hours:'Open daily · closes around 9:00 PM',delivery_fee:30,free_delivery_threshold:499,service_pincodes:['572107']};
export const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value);
const images:Record<number,string>={3:'curd',11:'parleg',12:'cocacola',13:'pepsi',23:'bisleri',25:'dettol',26:'lux',27:'dove',28:'ariel',29:'vim',31:'toordal',32:'johnson',1:'amul-milk',2:'amul-butter',4:'aashirvaad-atta',5:'india-gate-rice',6:'tata-salt',7:'fortune-oil',8:'tata-tea',9:'maggi',10:'good-day',14:'colgate',15:'surf-excel',16:'apples',17:'bananas',18:'tomatoes',19:'potatoes',20:'onions',21:'carrots',22:'oranges',24:'dairy-milk',30:'modernbread'};
for(const p of seedProducts){p.image=images[p.id]?`./products/${images[p.id]}.webp`:'';}
const categoryImages:Record<string,string>={fruits:'apples',dairy:'amul-milk',rice:'india-gate-rice',atta:'aashirvaad-atta',oil:'fortune-oil',snacks:'maggi',beverages:'tata-tea',chocolates:'dairy-milk',bakery:'modernbread',pulses:'toordal',baby:'johnson',personal:'colgate',household:'surf-excel'};
for(const c of seedCategories)c.image=categoryImages[c.id]?`./products/${categoryImages[c.id]}.webp`:'';
