'use client';
import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {onAuthStateChanged,signOut,type User} from 'firebase/auth';
import {toast} from 'sonner';
import type {SupabaseClient} from '@supabase/supabase-js';
import {seedProducts,seedCategories,defaultSettings,type Product,type Category} from './catalog';
import {services,ensureRole,readableError,type Config} from './services';
export type Cart=Record<string,number>;
export type Profile={uid:string;name:string;phone:string;address:{house:string;area:string;city:string;pin:string}};
export type Order={id:string;user_id:string;customer_name:string;phone:string;items:{id:number;name:string;unit:string;price:number;mrp:number;qty:number;image:string}[];subtotal:number;savings:number;delivery_fee:number;total:number;status:string;fulfilment:string;address:Profile['address'];created_at:string;payment_status:string};
type StoreType={products:Product[];categories:Category[];settings:typeof defaultSettings;cart:Cart;wish:number[];orders:Order[];profile:Profile|null;user:User|null;isAdmin:boolean;config:Config|null;db:SupabaseClient|null;mode:string;loading:boolean;loginOpen:boolean;setLoginOpen:(v:boolean)=>void;add:(id:number,delta?:number)=>void;remove:(id:number)=>void;toggleWish:(id:number)=>Promise<void>;refresh:()=>Promise<void>;saveProfile:(p:Profile)=>Promise<void>;logout:()=>Promise<void>;clearCart:()=>void;setOrders:React.Dispatch<React.SetStateAction<Order[]>>;};
const Context=createContext<StoreType|null>(null);
export function StoreProvider({children}:{children:React.ReactNode}){
 const [products,setProducts]=useState(seedProducts),[categories,setCategories]=useState(seedCategories),[settings,setSettings]=useState(defaultSettings),[cart,setCart]=useState<Cart>({}),[wish,setWish]=useState<number[]>([]),[orders,setOrders]=useState<Order[]>([]),[profile,setProfile]=useState<Profile|null>(null),[user,setUser]=useState<User|null>(null),[isAdmin,setIsAdmin]=useState(false),[config,setConfig]=useState<Config|null>(null),[db,setDb]=useState<SupabaseClient|null>(null),[mode,setMode]=useState('loading'),[loading,setLoading]=useState(true),[loginOpen,setLoginOpen]=useState(false);
 const hydrated=useRef(false),currentUser=useRef<string|null>(null),generation=useRef(0);
 async function refresh(){const {db}=await services();if(!db)return;const [p,c,s]=await Promise.all([db.from('products').select('*').order('id'),db.from('categories').select('*').order('sort_order'),db.from('store_settings').select('*').eq('id',1).single()]);if(p.error||c.error||s.error)throw Error('We could not load the store. Please try again.');setProducts(p.data.map(x=>({...x,image:x.image?.startsWith('/products/')?'.'+x.image:x.image,price:Number(x.price),mrp:Number(x.mrp)})));setCategories(c.data.map(x=>({...x,image:x.image?.startsWith('/products/')?'.'+x.image:x.image})));setSettings({...s.data,delivery_fee:Number(s.data.delivery_fee),free_delivery_threshold:Number(s.data.free_delivery_threshold)});}
 useEffect(()=>{let active=true;let unsubscribe=()=>{};
 try{const raw=JSON.parse(localStorage.getItem('vmart-cart-draft')||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))setCart(Object.fromEntries(Object.entries(raw).filter(([id,q])=>/^\d+$/.test(id)&&Number.isInteger(q)&&Number(q)>0&&Number(q)<=99)) as Cart);}catch{}
 services().then(async({config,auth,db})=>{if(!active)return;setConfig(config);setDb(db);setMode(db&&auth?'live':'preview');if(db){try{await refresh();}catch(e){setMode('unavailable');toast.error(readableError(e));}}setLoading(false);
 if(auth)unsubscribe=onAuthStateChanged(auth,async u=>{const run=++generation.current;hydrated.current=false;currentUser.current=u?.uid||null;setUser(u);setIsAdmin(false);setProfile(null);setWish([]);setOrders([]);if(!u){hydrated.current=true;return;}try{await ensureRole();const token=await u.getIdTokenResult();if(!active||run!==generation.current)return;setIsAdmin(token.claims.vmart_admin===true);if(db){const [p,c,w,o]=await Promise.all([db.from('profiles').select('*').eq('uid',u.uid).maybeSingle(),db.from('carts').select('items').eq('user_id',u.uid).maybeSingle(),db.from('wishlists').select('product_id').eq('user_id',u.uid),db.from('orders').select('*').eq('user_id',u.uid).order('created_at',{ascending:false})]);if([p,c,w,o].some(x=>x.error))throw Error('Your account could not be loaded. Please try signing in again.');if(!active||run!==generation.current)return;setProfile(p.data||{uid:u.uid,name:'',phone:u.phoneNumber||'',address:{house:'',area:'',city:'Tumakuru',pin:'572107'}});setWish((w.data||[]).map(x=>x.product_id));setOrders(o.data||[]);setCart(old=>({...old,...(c.data?.items||{})}));}if(run===generation.current)hydrated.current=true;}catch(e){toast.error(readableError(e));}});
 }).catch(e=>{setMode('unavailable');setLoading(false);toast.error(readableError(e));});return()=>{active=false;unsubscribe();};},[]);
 useEffect(()=>{if(loading)return;const uid=user?.uid;const timer=setTimeout(()=>{if(uid&&db&&hydrated.current&&currentUser.current===uid){void db.from('carts').upsert({user_id:uid,items:cart}).then(({error})=>{if(error)toast.error('Your basket could not be synced. Please try again.');});}else if(!uid){try{localStorage.setItem('vmart-cart-draft',JSON.stringify(cart));}catch{}}},400);return()=>clearTimeout(timer);},[cart,user,db,loading]);
 function add(id:number,delta=1){const p=products.find(x=>x.id===id);if(!p||!p.active)return;setCart(old=>{const n=(old[id]||0)+delta;if(n>Math.min(p.stock,99)){toast.error(`Only ${Math.min(p.stock,99)} available`);return old;}const next={...old};if(n<=0)delete next[id];else next[id]=n;return next;});}
 function remove(id:number){setCart(old=>{const n={...old};delete n[id];return n;});}
 async function toggleWish(id:number){if(!user){setLoginOpen(true);return;}if(!db){toast.error('Saved items are currently unavailable.');return;}const exists=wish.includes(id);const {error}=exists?await db.from('wishlists').delete().eq('user_id',user.uid).eq('product_id',id):await db.from('wishlists').insert({user_id:user.uid,product_id:id});if(error){toast.error('We could not update your saved items.');return;}setWish(a=>exists?a.filter(x=>x!==id):[...a,id]);}
 async function saveProfile(p:Profile){if(!db||!user)throw Error('Please sign in to save your details.');const {error}=await db.from('profiles').upsert({...p,uid:user.uid,phone:user.phoneNumber||''});if(error)throw error;setProfile({...p,phone:user.phoneNumber||''});}
 async function logout(){const {auth}=await services();currentUser.current=null;hydrated.current=false;setCart({});try{localStorage.removeItem('vmart-cart-draft');}catch{}if(auth)await signOut(auth);}
 function clearCart(){setCart({});try{localStorage.removeItem('vmart-cart-draft');}catch{}}
 return <Context.Provider value={{products,categories,settings,cart,wish,orders,profile,user,isAdmin,config,db,mode,loading,loginOpen,setLoginOpen,add,remove,toggleWish,refresh,saveProfile,logout,clearCart,setOrders}}>{children}</Context.Provider>;
}
export function useStore(){const c=useContext(Context);if(!c)throw Error('Store provider missing');return c;}
